### ISSUE TITLE
Model assessment and indices of fit

### ISSUE THREAD

**Issue by DominiqueMakowski** [itsdfish/SequentialSamplingModels.jl#44]
I am going through [Myers (2022)](https://www.frontiersin.org/articles/10.3389/fpsyg.2022.1039172/full#tab6) and on the model goodness-of-fit section. 

They mention different methods to compare models together, and I am to figure out how to do that using SSM & Turing. Apologies if that's slightly out of your depth, but I thought I'd start a discussion to help users achieve this critical step of their analysis.

## Maximum Log Likelihood (LLE)

One of the most basic methods seems to be the max LLE.

### For a target distribution

If I'm not mistaken, computing the max LLE between "observed" data and a distribution with known parameter is showcased in the example in [rtdists](https://github.com/rtdists/rtdists/#get-started):

```r
objective_fun <- function(par, rt, response, distribution = "norm") {
  ...
  # get summed log-likelihood:
  d <- do.call(dLBA, args = c(rt=list(rt), response=list(response), spar, dist_par, 
                               distribution=distribution, silent=TRUE))
  if (any(d == 0)) return(1e6)
  else return(-sum(log(d)))
}
```

Am I correct in assuming that the equivalent can be obtained in SSM as follows:

```julia
m = LBA(ν=[2.4, 1.6], A=0.5, k=0.5, τ=0.5)
choice, rt = rand(m, 500)

-sum(logpdf.(m, choice, rt))
```

### For a Turing model

A Turing chain has 2 (internal) parameters; `lp` and `log_density`

```julia
DataFrame(chain)[!, :log_density]
```

Which are the same. Do these correspond to the above? And do their mean/median would give us a reasonable goodness-of-fit index?

## BIC / DIC

BIC (`BIC = k*ln(n) − 2*LLE`) is mentioned as a better index than the raw LLE. It is trivial to compute once we have LLE, but Turing has a [method](https://turinglang.org/MCMCChains.jl/stable/modelstats/) to compute DIC.

Thei method requires however to pass a function, that in the example they define as:

```julia
lpfun = function f(chain::Chains) # function to compute the logpdf values
    niter, nparams, nchains = size(chain)
    lp = zeros(niter + nchains) # resulting logpdf values
    for i = 1:nparams
        lp += map(p -> logpdf( ... , x), Array(chain[:,i,:]))
    end
    return lp
end

DIC, pD = dic(chain, lpfun)
```

That said I am not sure what to input in the `...` of logpdf 🤔 

Any thoughts or pointers are welcome!

**Comment by itsdfish** [comment]
In your example above for LLE, you should drop the `-` unless you are using the model with an optimization algorithm that minimizes an objective function. Aside from that, it is correct. You could also use `loglikelihood`:

```
dist = LBA()
data = rand(dist, 10)
loglikelihood(dist, data)
```

For information criteria, when you use optimize via Turing, it returns a `StatisticalModel`, which means you should be able to call methods define in [StatsBase.jl ](https://juliastats.org/StatsBase.jl/0.19.1/statmodels.html#StatsBase.bic)

I'm not too familiar with DIC, unfortunately. It might be worth opening a question on Discourse if the documentation is unclear. 

I recommend using `loo` instead of the alternatives above. You can find an implementation that should work with Turing here: https://turinglang.org/ParetoSmooth.jl/dev/. I think the documentation could benefit from a MWE. 

Andrew Gelman recommends `loo`, but here are some criticisms (see below).

Gronau, Q. F., & Wagenmakers, E. J. (2019). Limitations of Bayesian leave-one-out cross-validation for model selection. Computational brain & behavior, 2, 1-11.

**Comment by DominiqueMakowski** [comment]
See https://discourse.julialang.org/t/compare-two-turing-models-with-loo-se-is-nan/102269/
