### ISSUE TITLE
ExGaussian: lower limit of Tau is ~.005?

### ISSUE THREAD

**Issue by DominiqueMakowski** [itsdfish/SequentialSamplingModels.jl#81]
I noticed something quite odd which, if not a bug, should probably be documented.

The ExGaussian distribution behaves weirdly when Tau <= .005:

```jl
using Makie
using Distributions, SequentialSamplingModels

x = range(-0.1, 2, length=1000)
f = lines(x, pdf.(ExGaussian(0.5, 0.2, 0.05), x); color="red")
lines!(x, pdf.(ExGaussian(0.5, 0.2, 0.006), x); color="blue")
lines!(x, pdf.(ExGaussian(0.5, 0.2, 0.005), x); color="green", linewidth=6)
f
```

![image](https://github.com/itsdfish/SequentialSamplingModels.jl/assets/8875533/7c6cbd51-b9aa-4b50-a702-3544cf0d4f36)

And basically shows all Nans when Tau = 0

**Comment by itsdfish** [comment]
The exponetial distribution is defined for tau > 0. You can see the problem [here](https://github.com/itsdfish/SequentialSamplingModels.jl/blob/2677f6c561b670364fa389487f5cae214b06b2a9/src/ex_gaussian.jl#L69C17-L69C18) where 1 / tau. 

The issue is numerical stability for tau <= .005. For example, 


```
rt = .5 
μ, σ, τ = 0.5, 0.2, 0.005
(0.5, 0.2, 0.005)

exp((μ - rt) / τ + (σ^2 / 2τ^2))
```
Which results in Inf because (μ - rt) / τ becomes large as the difference in the numerator increases.  The formulation of `logpdf` is more numerically stable:

```
julia> exp(logpdf(ExGaussian(0.5, 0.2, 0.005), 0.5))
1.9934670376605403
```

I will release a patch version which exponentiates `logpdf`. That should take care of most issues.

**Comment by itsdfish** [comment]
Version .11.5 should be available in about 20 minutes. 

The plot looks correct. 

```
using SequentialSamplingModels
using Plots 

x = range(-0.1, 2, length=1000)
plot(x, pdf.(ExGaussian(0.5, 0.2, 0.05), x))
plot!(x, pdf.(ExGaussian(0.5, 0.2, 0.005), x))
savefig("example.png")
```
![example](https://github.com/itsdfish/SequentialSamplingModels.jl/assets/9677184/2e0d65a9-2d1c-43ae-9959-736489b68a00)

**Comment by DominiqueMakowski** [comment]
legend

**Comment by itsdfish** [comment]
> legend

I do it for the children, but it turns out they don't care about SSMs.
